# Generated by Django 5.0.7 on 2024-07-27 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotasAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_html', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('status_publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota de Aula',
                'verbose_name_plural': 'Notas de Aula',
            },
        ),
    ]
