# Generated by Django 5.0.7 on 2024-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_caminho_url_notasaula_caminho_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasaula',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='img/post/<django.db.models.fields.SlugField>/'),
        ),
    ]
